# Generated by Django 4.0.5 on 2022-09-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='document',
            field=models.FileField(null=True, upload_to='', verbose_name='Документ'),
        ),
    ]
