# Generated by Django 4.1 on 2022-09-14 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0017_alter_position_options_alter_timesheet_datasheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='dataSheet',
            field=models.DateField(default='2022-09-14', verbose_name='Дата'),
        ),
    ]
