# Generated by Django 4.1.2 on 2022-10-10 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0020_alter_timesheet_datasheet'),
        ('plan', '0024_alter_act_id_alter_buyer_id_alter_model_product_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='guild',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='salary.department', verbose_name='Участок'),
        ),
    ]
