# Generated by Django 4.1.2 on 2022-10-10 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0025_alter_plan_guild'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plot',
        ),
    ]
